version: '3'
services:
  # FRONTEND
  client-service:
    image: node:14
    command: bash -c "yarn install && yarn start"
    environment:
      CI: 'true'
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    restart: on-failure
    working_dir: /opt/app
    volumes:
      - ./client-service:/opt/app
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    depends_on:
      - api-service
  # API Server
  api-service:
    image: node:14
    command: bash -c "yarn install && yarn start"
    environment:
      PORT: ${API_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    restart: unless-stopped
    working_dir: /opt/app
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./api-service:/opt/app
      - /opt/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
volumes:
  db_data: